# Use root/example as user/password credentials
version: '3.8'

services:
  api:
    restart: 
      always
    networks:
      - backbone
    image: daum1820/hbl-api
    build:
      context: ./api
      target: production
      dockerfile: ./Dockerfile
    environment: 
      MONGODB_URI: mongodb://mongo:27017/hbl-db
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 5m
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 8h
    ports:
      - '3000:3000'
  ui:
    restart: 
      always
    networks:
      - backbone
    image: daum1820/hbl-ui
    build:
      context: ./ui
      target: production
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - backbone
    ports:
      - 8081:8081
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - backbone
    ports:
      - 27017:27017
    volumes:
      - hbl-mongo-vol:/data/db
      - hbl-mongo-config-vol:/data/configdb
volumes:
  hbl-mongo-vol:
    external: true
  hbl-mongo-config-vol:
    external: true

networks:
  backbone:
    driver: bridge