version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_HBL
          aws-access-key-id: ACCESS_KEY_ID_HBL
          aws-secret-access-key: SECRET_ACCESS_KEY_HBL
          context: hbl-aws
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./ui
          profile-name: production
          region: AWS_REGION_HBL
          repo: hbl-ui
          skip-when-tags-exist: false
          tag: 'ui-latest'
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_HBL
          aws-access-key-id: ACCESS_KEY_ID_HBL
          aws-secret-access-key: SECRET_ACCESS_KEY_HBL
          context: hbl-aws
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./api
          profile-name: production
          region: AWS_REGION_HBL
          repo: hbl-api
          skip-when-tags-exist: false
          tag: 'api-latest'